"""phase3 relationships versions amendments

Revision ID: 3009b08632a1
Revises: 0002_slice
Create Date: 2026-09-21 08:40:47.902137
"""
from alembic import op
import sqlalchemy as sa


revision = '0003_graph'
down_revision = '0002_slice'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_amendments',
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('amendment_no', sa.String(length=48), nullable=False),
    sa.Column('amendment_date', sa.Date(), nullable=True),
    sa.Column('affected_clauses', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_amendments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_amendments_standard_id'), ['standard_id'], unique=False)

    op.create_table('standard_versions',
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=48), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_versions_standard_id'), ['standard_id'], unique=False)

    op.create_table('standard_relationships',
    sa.Column('from_standard_id', sa.String(length=36), nullable=False),
    sa.Column('to_standard_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('relationship_confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_standard_id', 'to_standard_id', 'relationship_type', name='uq_relationship')
    )
    with op.batch_alter_table('standard_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_relationships_from_standard_id'), ['from_standard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_relationships_to_standard_id'), ['to_standard_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_relationships_to_standard_id'))
        batch_op.drop_index(batch_op.f('ix_standard_relationships_from_standard_id'))

    op.drop_table('standard_relationships')
    with op.batch_alter_table('standard_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_versions_standard_id'))

    op.drop_table('standard_versions')
    with op.batch_alter_table('standard_amendments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_amendments_standard_id'))

    op.drop_table('standard_amendments')
    # ### end Alembic commands ###
