"""phase4 audit

Revision ID: 6b42a0a74962
Revises: 0003_graph
Create Date: 2026-09-21 13:31:02.964303
"""
from alembic import op
import sqlalchemy as sa


revision = '0004_audit'
down_revision = '0003_graph'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('parameter', sa.String(length=48), nullable=False),
    sa.Column('value_a', sa.String(length=64), nullable=False),
    sa.Column('unit_a', sa.String(length=24), nullable=False),
    sa.Column('source_a', sa.String(length=64), nullable=False),
    sa.Column('value_b', sa.String(length=64), nullable=False),
    sa.Column('unit_b', sa.String(length=24), nullable=False),
    sa.Column('source_b', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('gaps',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('gap_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_standard_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('is_mandatory_claim', sa.Boolean(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gaps_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('coverage_results',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('coverage', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_results_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_results_analysis_id'))

    op.drop_table('coverage_results')
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gaps_analysis_id'))

    op.drop_table('gaps')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_analysis_id'))

    op.drop_table('conflicts')
    # ### end Alembic commands ###
