"""phase5 regulatory

Revision ID: 94d888b44ad5
Revises: 0004_audit
Create Date: 2026-09-21 13:35:49.166602
"""
from alembic import op
import sqlalchemy as sa


revision = '0005_regulatory'
down_revision = '0004_audit'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_records',
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('scheme', sa.String(length=24), nullable=False),
    sa.Column('product_description', sa.String(length=300), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certification_records_standard_id'), ['standard_id'], unique=False)

    op.create_table('qco_records',
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('product_description', sa.String(length=300), nullable=False),
    sa.Column('qco_status', sa.String(length=16), nullable=False),
    sa.Column('order_name', sa.String(length=300), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('retrieved_at', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qco_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qco_records_standard_id'), ['standard_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qco_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qco_records_standard_id'))

    op.drop_table('qco_records')
    with op.batch_alter_table('certification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certification_records_standard_id'))

    op.drop_table('certification_records')
    # ### end Alembic commands ###
